'use client';
import {useState,useEffect,useRef} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {ArrowUpRight,ArrowRight,Plus,MapPin,Menu,X,Languages,ScanLine,Stethoscope,HeartPulse,Check,Copy} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {TripGallery} from '@/components/trip-gallery';
import {RoutePlanner} from '@/components/route-planner';
import {Questions} from '@/components/questions';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
// Ссылки на каналы отделены от прямого звонка координатору.
const TG='https://t.me/medicHeihe';
const MAX='https://max.ru/join/GmVp_ktKIVCAlDivnqMCdfUfc-4WoAVSGc2o819oxpg';
const news='https://ampravda.ru/2026/05/15/pokupka-biletov-na-teploxody-iz-blagoveshhenska-v-xeixe-stala-dostupna-onlain';
const reviews=[
{name:'Татьяна',date:'23 июля',text:'Ребята встретили, заселили в гостиницу, возили в клинику и обратно, а также чудесно поводили по экскурсиям.',more:'Огромная благодарность Олесе и Александру за потрясающую организацию поездки на лечение в Китай! Ребята встретили, заселили в гостиницу, возили в клинику и обратно, а также чудесно поводили по экскурсиям. Само лечение прошло выше всяких похвал: сделали КТ, врачи работают в идеальной чистоте с одноразовыми расходниками. Несмотря на языковой барьер (спасибо отличному переводчику), мы прекрасно понимали друг друга. Весь сложный объем работ занял ровно пять дней без потери качества. Зубы сделаны превосходно!',topic:'Лечение и сопровождение'},
{name:'Александра',date:'27 июня',text:'Хотим выразить благодарность Олесе и Александру за организацию, сопровождение и всевозможную помощь.',more:'Доброе утро. Хотим выразить благодарность Олесе и Александру за организацию, сопровождение и всевозможную помощь при вставлении зубов, нахождении в Хэй-Хэ. Все прошло прекрасно, муж доволен!',topic:'Поездка в Хэйхэ'},
{name:'Ксения',date:'Из чата MAX',text:'Олеся не просто переводчик, а настоящий помощник. Она знает лучшие места для шопинга, решает любые бытовые вопросы.',more:'Поездка в приграничный китайский город Хэйхэ стала для нас незабываемой благодаря гиду Олесе. В отличие от стандартных экскурсоводов, она показала не туристический фасад, а настоящую жизнь города: мы ели различные блюда в местных кафешках и гуляли по набережной Амура с китайской стороны. Олеся не просто переводчик, а настоящий помощник. Она знает лучшие места для шопинга, решает любые бытовые вопросы.',topic:'Знакомство с городом'},
{name:'Отзыв из сообщества',date:'Имя на скриншоте не указано',text:'Это была не просто стоматологическая поездка, а настоящий мини-спа-тур.',more:'Сделали протезирование. Между приёмами у врача успела: иглоукалывание, массаж, чистка лица. Это была не просто стоматологическая поездка, а настоящий мини-спа-тур.',topic:'Впечатления о поездке'}];
const services=[['Протезирование','Коронки из диоксида циркония, металлокерамика, мостовидные и съёмные протезы.'],['Имплантация и хирургия','Установка имплантов, удаление зубов и подготовка к протезированию.'],['Лечение зубов','Лечение кариеса, пульпита и корневых каналов. Восстановление формы зуба.'],['Эстетика улыбки','Виниры, профессиональная гигиена, отбеливание и исправление прикуса.']];
export default function Page(){
 const [menu,setMenu]=useState(false),[selected,setSelected]=useState<number|null>(null),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);const reduce=useReducedMotion();
 const [activeSection,setActiveSection]=useState('');
 const reviewTitle=useRef<HTMLHeadingElement|null>(null);
 const reviewTrigger=useRef<HTMLButtonElement|null>(null),menuTrigger=useRef<HTMLButtonElement|null>(null);

 // Наблюдатель подсвечивает раздел без обработки каждого события прокрутки.
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActiveSection(e.target.id)},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);menuTrigger.current?.focus()}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu]);
 useEffect(()=>{if(!copied)return;const timer=setTimeout(()=>setCopied(false),3500);return()=>clearTimeout(timer)},[copied]);
 const reveal={initial:{opacity:0,y:reduce?0:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.12},transition:{duration:reduce?0:.65}};
 async function copyAddress(){try{await navigator.clipboard.writeText('黑河市爱辉区王肃街112号');setCopied(true);setCopyError(false)}catch{setCopyError(true)}}
 return <><a className="skip" href="#main">К содержанию</a><header><a href="#" className="brand" aria-label="Жуйкан, на главную"><span className="brand-mark"><Plus/></span><span>ЖУЙКАН<small>瑞康综合门诊</small></span></a><nav aria-label="Основная навигация">{[['about','О центре'],['services','Лечение'],['route','Маршрут'],['moments','Наши поездки'],['reviews','Отзывы']].map(([id,label])=><a key={id} href={'#'+id} aria-current={activeSection===id?'location':undefined}>{label}</a>)}</nav><a className="header-contact" href="tel:+79246810698">+7 924 681-06-98 <ArrowUpRight size={17}/></a><Button variant="ghost" className="menu-toggle" ref={menuTrigger} aria-controls="mobile-navigation" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></header>{menu&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Мобильная навигация">{[['#about','О центре'],['#services','Направления'],['#route','Как добраться'],['#moments','Наши поездки'],['#reviews','Отзывы'],['#contact','Контакты']].map(([link,label])=><a key={link} href={link} onClick={()=>{setMenu(false);requestAnimationFrame(()=>{const target=document.querySelector(link) as HTMLElement|null;target?.setAttribute('tabindex','-1');target?.focus({preventScroll:true})})}}>{label}<ArrowUpRight/></a>)}</nav>}
 <main id="main"><section id="home" className="hero wrap"><motion.div {...reveal} initial={false} className="hero-copy"><div className="eyebrow">МЕДИЦИНСКИЙ ЦЕНТР В ХЭЙХЭ</div><h1>Ближе к вам.<br/><span>Ближе к здоровью.</span></h1><div className="hero-bottom"><p>Стоматология и забота о здоровье в Китае.<br/>С поддержкой на русском языке.</p><Button asChild className="cta"><a href="#contact">Обсудить лечение и поездку <ArrowUpRight/></a></Button></div></motion.div><motion.figure {...reveal} initial={false} className="hero-photo"><img src="./clinic.jpg" alt="Фасад медицинского центра Жуйкан в Хэйхэ" fetchPriority="high" width="1280" height="706"/></motion.figure><div className="photo-caption"><span>Хэйхэ, Китай · ул. Ван Су, 112</span><a href="#route">На другом берегу Амура <ArrowRight size={16}/></a></div></section>
 <section id="about" className="wrap about"><motion.div {...reveal}><p className="section-label">ЗНАКОМЬТЕСЬ, ЖУЙКАН</p><h2>Вы занимаетесь здоровьем.<br/><span>Мы помогаем с поездкой.</span></h2><p className="intro">Многопрофильный центр в Хэйхэ объединяет стоматологию, диагностику и восстановительные процедуры. Координаторы помогут организовать встречу, проживание и сопровождение в клинике.</p></motion.div><motion.div {...reveal} className="facts"><div><span className="fact-number">2012</span><p>год основания центра*</p></div><div><span className="fact-number">3 000<span> м²</span></span><p>пространства для заботы*</p></div><div><Languages/><h3>На вашем языке</h3><p>Русскоговорящие сотрудники и помощь переводчика.</p></div></motion.div><p className="fine">* По информации исходного сайта клиники.</p><div className="care-strip"><span><ScanLine/> КТ и цифровое сканирование</span><span><Stethoscope/> Своя зуботехническая лаборатория</span><span><Languages/> Сопровождение на русском</span></div></section>
 <section id="services" className="services-section"><div className="wrap"><motion.div {...reveal}><p className="section-label">НАПРАВЛЕНИЯ</p><h2>Всё начинается<br/>с вашей улыбки.</h2></motion.div><div className="services-layout"><motion.div {...reveal} className="service-lead"><Stethoscope size={44} strokeWidth={1.2}/><h3>Стоматология</h3><p>От диагностики до восстановления улыбки. План, сроки и стоимость лечения определяются после консультации врача.</p><a href="#contact" className="text-link">Задать вопрос <ArrowUpRight size={18}/></a></motion.div><Accordion type="single" collapsible defaultValue="0" className="service-list">{services.map(([title,text],i)=><AccordionItem value={String(i)} key={title}><AccordionTrigger><span className="service-number">0{i+1}</span><span>{title}</span></AccordionTrigger><AccordionContent><p>{text}</p><a href="#contact" className="text-link">Обсудить направление <ArrowUpRight size={17}/></a></AccordionContent></AccordionItem>)}</Accordion></div><div className="other-care"><HeartPulse size={30}/><div><h3>Больше, чем стоматология</h3><p>Диагностика и УЗИ · Косметология · Физиотерапия · Консультации терапевта</p></div></div></div></section>
 <section id="route" className="wrap route"><motion.div {...reveal}><p className="section-label">БЛАГОВЕЩЕНСК → ХЭЙХЭ</p><h2>Другой берег.<br/><span>Понятный маршрут.</span></h2><p className="intro">Начните с разговора с координатором. Согласуйте дату, способ пересечения границы и встречу на китайской стороне.</p></motion.div><RoutePlanner/><div className="route-note"><p>Перед покупкой билетов уточните документы для въезда с вашей целью поездки, расписание, стоимость и место посадки. Зимой схема речной переправы меняется.</p><a href={news} target="_blank" rel="noreferrer">Источник: «Амурская правда», 15.05.2026 <ArrowUpRight size={15}/></a></div><div className="steps"><div><span>01</span><h3>Свяжитесь с нами</h3><p>Расскажите о задаче и желаемых датах.</p></div><div><span>02</span><h3>Согласуйте поездку</h3><p>Уточните маршрут, проживание и встречу.</p></div><div><span>03</span><h3>Приезжайте в Хэйхэ</h3><p>Координатор поможет добраться до центра.</p></div><div><span>04</span><h3>Получите план лечения</h3><p>Врач проведёт осмотр и предложит варианты.</p></div></div></section>
 <TripGallery/><section id="reviews" className="reviews-section"><div className="wrap"><motion.div {...reveal}><p className="section-label">ЛИЧНЫЙ ОПЫТ</p><h2>Истории тех,<br/>кто уже приехал.</h2><p className="intro">Отзывы из нашего сообщества в MAX. Личные впечатления пациентов и гостей Хэйхэ.</p></motion.div><div className="reviews-grid">{reviews.map((r,i)=><motion.article {...reveal} key={r.name} className="review"><span className="quote-sign">“</span><p className="review-topic">{r.topic}</p><blockquote>{r.text}</blockquote><div className="review-author"><span className="avatar">{i===3?'Ж':r.name[0]}</span><div><strong>{r.name}</strong><small>{r.date}</small></div></div><Button variant="ghost" onClick={(e)=>{reviewTrigger.current=e.currentTarget;setSelected(i)}} className="review-read">Читать отзыв <ArrowUpRight size={17}/></Button></motion.article>)}</div><p className="fine">Отзывы передают личный опыт участников поездок. Результаты и сроки лечения индивидуальны.</p></div></section>
 <Questions/><section id="contact" className="wrap contact"><motion.div {...reveal}><p className="section-label">БУДЕМ НА СВЯЗИ</p><h2>Ваш первый шаг<br/><span>к поездке в Хэйхэ.</span></h2><p className="intro">Позвоните, чтобы обсудить лечение и организацию поездки. Новости клиники и общение с участниками в наших каналах.</p><a href="tel:+79246810698" className="big-phone">+7 924 681-06-98 <ArrowUpRight/></a><div className="socials"><Button asChild className="cta"><a href={TG} target="_blank" rel="noreferrer">Telegram-канал <ArrowUpRight/></a></Button><Button asChild variant="outline" className="cta secondary"><a href={MAX} target="_blank" rel="noreferrer">Сообщество в MAX <ArrowUpRight/></a></Button></div></motion.div><motion.div {...reveal} className="address"><MapPin size={30}/><h3>Ждём вас в Жуйкан</h3><p>Китай, провинция Хэйлунцзян,<br/>Хэйхэ, район Айхуэй,<br/>ул. Ван Су, 112</p><p lang="zh">黑河市爱辉区王肃街112号</p><Button variant="ghost" className="copy" onClick={copyAddress}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Адрес скопирован':'Скопировать для водителя'}</Button><p role="status" className="fine">{copyError?'Не удалось скопировать. Выделите китайский адрес выше.':copied?'Китайский адрес скопирован.':''}</p><div className="hours">Ежедневно · 08:00–22:00<small>Время и адрес указаны на исходном сайте.<br/>Подтвердите запись перед визитом.</small></div></motion.div></section></main><footer className="wrap"><a className="brand" href="#"><span className="brand-mark"><Plus/></span><span>ЖУЙКАН<small>瑞康综合门诊</small></span></a><p>© 2026 · Медицинский центр в Хэйхэ</p><a href="#main">Наверх ↑</a><div className="medical-note">Имеются противопоказания. Необходима консультация специалиста.</div></footer>
 <Dialog open={selected!==null} onOpenChange={open=>!open&&setSelected(null)}><DialogContent onOpenAutoFocus={e=>{e.preventDefault();reviewTitle.current?.focus({preventScroll:true})}} className="review-dialog" onCloseAutoFocus={e=>{e.preventDefault();reviewTrigger.current?.focus()}}>{selected!==null&&<><DialogTitle ref={reviewTitle} tabIndex={-1}>{reviews[selected].name}</DialogTitle><DialogDescription>{reviews[selected].topic} · MAX</DialogDescription><p>{reviews[selected].more}</p></>}</DialogContent></Dialog></>;
}
